---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: retrieve information about log file
      stat:
        path: /var/log/elasticsearch/elasticsearch.log
      register: elasticsearch_log
    - name: check file exist
      assert:
        that: "elasticsearch_log.stat.exists"
    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        url: http://localhost:9200
        return_content: yes
      register: this
    - name: Web answer
      assert:
        that: "'You Know, for Search' in this.content"
    - name: Example assertion
      assert:
        that: true
