---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: centos7
    box: bento/centos-7
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
